### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by rebub** [Kacarott/scroll-fade#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [scroll-fade](https://github.com/Kacarott/scroll-fade) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\reub\.atom\packages\scroll-fade\lib\scroll-fade.js:19

TypeError: Cannot read property 'element' of undefined
    at /packages/scroll-fade/lib/scroll-fade.js:19:52
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at TextEditorComponent.setScrollTop (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:115888)
    at TextEditorComponent.setScrollTopRow (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:116842)
    at TextEditorComponent.flushPendingLogicalScrollPosition (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:100306)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:91700)
    at TextEditorComponent.didAttach (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:90852)
    at HTMLElement.attachedCallback (/app.asar/src/text-editor-element.js:43:25)
    at HTMLElement.rootChanged (/app.asar/src/pane-container-element.js:28:12)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at PaneContainer.setRoot (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:445075)
    at PaneContainer.deserialize (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:443535)
    at WorkspaceCenter.deserialize (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:45005)
    at Workspace.deserialize (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:423739)
    at AtomEnvironment.deserialize (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:750850)
    at AtomEnvironment.attemptRestoreProjectStateForPaths (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:748646)
    at AtomEnvironment.openLocations (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:753703)
```

### Commands

```
     -0:16.4.0 application:open-folder (input.hidden-input)
```

### Non-Core Packages

```
scroll-fade 0.2.1 
seti-ui 1.11.0 
```

**Comment by Kacarott** [comment]
Thanks for the bug report. I've just pushed through a patch that I think should solve it. Can you confirm that it's fixed?
